### PR TITLE
Replace all instances of "RPG" with "RGP"

### PR DESCRIPTION
**Pull request by WeirdAlex03**
I fixed the typo, but the other way around

### CODE REVIEW

**Comment by WeirdAlex03** [comment]
@emilkovacev I am calling your bluff. **Merge. The. PR.**

**Comment by Sploder12** [comment]
Im on board with this.

**Comment by emilkovacev** [comment]
This is truly the spookiest PR I've seen all year 🎃

**Comment by WeirdAlex03** [comment]
The madlad actually did it!

**Pull request merged**
