### PR TITLE
Start style enforcement

### PR DESCRIPTION
**Pull request by WeirdAlex03**
This adds the Conventional Commit plugin and style config files. More details can be found in the commit messages

This PR also includes the first 2 commits following conventional commits styles, with hopefully many more to follow

### CODE REVIEW

**Review by bicknrown — APPROVED** [review]
this looks good to me, but i'd like another set of eyes.

**Comment by jakesavi** [comment]
Looks good to me

**Review by jakesavi — APPROVED** [review]
Can we implement this on other projects?

**Comment by WeirdAlex03** [comment]
> Can we implement this on other projects?

Idk what the other teams are using, but that extension is also available for VSC and maybe a few other IDEs. I personally use ESLint for JS code

**Pull request merged**
