### PR TITLE
Game audio

### PR DESCRIPTION
**Pull request by Upside-Sandwich**
Proposed changes
-------------------------------------------
Describe the big picture of your changes here to communicate to the maintainers why we should accept this pull request. If it fixes a bug or resolves a feature request, be sure to link to that issue.

Types of changes
-------------------------------------------
What types of changes does your code introduce?
_Put an `x` in the boxes that apply_

- [ ] Bugfix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] Documentation Update (if none of the other choices apply)

Checklist
-------------------------------------------
_Put an `` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. This is simply a reminder of what we are going to look for before merging your code._

- [ ] My changeset covers only what is described above (no extraneous changes)
- [ ] Lint and unit tests pass locally with my changes
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added necessary documentation (if appropriate)
- [ ] Any dependent changes have been merged downstream

Further comments
-------------------------------------------
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...x

### CODE REVIEW

**Comment by emilkovacev** [comment]
Only one requested change – can you change the naming convention of the files from `camelCase` to `snake_case`?

**Comment by emilkovacev** [comment]
Additionally (while not required) I think it would be cool if you maintained a README.md file in the rpgAudio directory, detailing what you intend each sound to be for!

**Comment by Upside-Sandwich** [comment]
I will get on that once I figure out how to update my file on Git.

**Comment by WeirdAlex03** [comment]
I don't believe it's possible to rename them on GitHub, if that's what you mean. But if you have the repo on your computer, you can just rename them as normal and commit/push to your fork. Then you'll see the commit in the timeline here

I do have questions about naming though. Namely, why are all the file names prefixed with an `a`? Also, I think it might be better just to call the folder `audio`. Then we can use the same folder for any other sounds we might want (and these current ones can be moved to `audio/rpg/` if need be)

**Comment by Upside-Sandwich** [comment]
The naming conventions are purely for my own organization while the files
are on my computer. I can make them normal.

**Comment by Upside-Sandwich** [comment]
I'll be real, that took me way too long to do. Sorry.

**Pull request merged**
